-- MTAANI POS hard reset.
-- This intentionally deletes existing POS tables so the database can be rebuilt
-- from the current single-shop schema.sql without legacy multi-location columns.

DROP TABLE IF EXISTS branches;
DROP TABLE IF EXISTS auditLogs;
DROP TABLE IF EXISTS billingPayments;
DROP TABLE IF EXISTS billingInvoices;
DROP TABLE IF EXISTS billingAccounts;
DROP TABLE IF EXISTS whatsappConversationTurns;
DROP TABLE IF EXISTS whatsappOutboundMessages;
DROP TABLE IF EXISTS whatsappPendingActions;
DROP TABLE IF EXISTS whatsappWebhookMessages;
DROP TABLE IF EXISTS whatsappContacts;
DROP TABLE IF EXISTS aiUsage;
DROP TABLE IF EXISTS idempotencyKeys;
DROP TABLE IF EXISTS deviceSyncStatus;
DROP TABLE IF EXISTS financialAccounts;
DROP TABLE IF EXISTS expenseAccounts;
DROP TABLE IF EXISTS mpesaCallbacks;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS salesTills;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS purchaseOrders;
DROP TABLE IF EXISTS stockAdjustmentRequests;
DROP TABLE IF EXISTS dailySummaries;
DROP TABLE IF EXISTS creditNotes;
DROP TABLE IF EXISTS supplierPayments;
DROP TABLE IF EXISTS suppliers;
DROP TABLE IF EXISTS salesInvoices;
DROP TABLE IF EXISTS serviceItems;
DROP TABLE IF EXISTS customerPayments;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS hrPayrollAdjustments;
DROP TABLE IF EXISTS hrAttendance;
DROP TABLE IF EXISTS hrStaffDocuments;
DROP TABLE IF EXISTS hrStaff;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS stockMovements;
DROP TABLE IF EXISTS endOfDayReports;
DROP TABLE IF EXISTS shifts;
DROP TABLE IF EXISTS refunds;
DROP TABLE IF EXISTS cashPicks;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS productIngredients;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS businesses;
DROP TABLE IF EXISTS loginAttempts;
