name = "mtaani-pos"
compatibility_date = "2024-04-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "mtaani_pos_db"
database_id = "9b66d200-8a63-423b-883f-fefee3259bab"

[[kv_namespaces]]
binding = "IMAGES_KV"
id = "9861e4885e1b4ce4bb79a2534d88f2ab"

[ai]
binding = "AI"
