import { jsPDF } from 'jspdf';

// ─── Layout ───────────────────────────────────────────────────────────────────
const M = 14;          // page margin mm
const W = 210 - M * 2; // content width (A4)

// ─── Color helpers ────────────────────────────────────────────────────────────
type RGB = [number, number, number];
const slate900: RGB = [15, 23, 42];
const slate600: RGB = [71, 85, 105];
const slate400: RGB = [148, 163, 184];
const slate100: RGB = [241, 245, 249];
const white: RGB    = [255, 255, 255];
const green:  RGB = [22, 163, 74];
const red:    RGB = [220, 38, 38];
const orange: RGB = [234, 88, 12];
const blue:   RGB = [37, 99, 235];
const purple: RGB = [88, 28, 135];

const sf = (d: jsPDF, c: RGB) => d.setFillColor(c[0], c[1], c[2]);
const st = (d: jsPDF, c: RGB) => d.setTextColor(c[0], c[1], c[2]);
const sd = (d: jsPDF, c: RGB) => d.setDrawColor(c[0], c[1], c[2]);

// ─── Shared drawing primitives ────────────────────────────────────────────────
function banner(doc: jsPDF, title: string, ref: string, date: string, bizName = 'MTAANI POS'): number {
  sf(doc, slate900);
  doc.rect(M, 10, W, 35, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  st(doc, white);
  doc.text(bizName.toUpperCase(), M + 5, 22);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  st(doc, slate400);
  doc.text('Mtaani Street, Nairobi CBD, Kenya', M + 5, 29);
  doc.text('Email: hello@mtaanipos.co.ke | Tel: +254 700 123 456', M + 5, 34);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  st(doc, white);
  doc.text(title.toUpperCase(), M + W - 5, 21, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  st(doc, slate400);
  doc.text('DOCUMENT REF: ' + ref, M + W - 5, 29, { align: 'right' });
  doc.text('DATE: ' + date, M + W - 5, 34, { align: 'right' });

  return 52; // y after header
}

function hLine(doc: jsPDF, y: number): number {
  sd(doc, slate100);
  doc.setLineWidth(0.3);
  doc.line(M, y, M + W, y);
  return y + 6;
}

function kvRow(doc: jsPDF, label: string, value: string, y: number, valC: RGB = slate900): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  st(doc, slate400);
  doc.text(label.toUpperCase() + ':', M, y);
  doc.setFont('helvetica', 'normal');
  st(doc, valC);
  doc.text(value || '—', M + 35, y); // Aligned to a fixed offset for better look
  return y + 6;
}

/** Manual table with borders */
function table(
  doc: jsPDF,
  headers: string[],
  colW: number[],
  rows: string[][],
  y: number
): number {
  const RH = 8;
  const xs: number[] = [M];
  colW.forEach((w, i) => xs.push(xs[i] + w));

  // Header
  sf(doc, slate900);
  doc.rect(M, y, W, RH, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  st(doc, white);
  headers.forEach((h, i) => {
    const isRight = i >= 2;
    const tx = isRight ? xs[i] + colW[i] - 2 : xs[i] + 2;
    doc.text(h, tx, y + 5.5, { align: isRight ? 'right' : 'left' });
  });
  y += RH;

  // Rows
  doc.setLineWidth(0.1);
  sd(doc, slate100);
  rows.forEach((cells, ri) => {
    if (ri % 2 === 0) {
      sf(doc, [250, 252, 255] as RGB);
      doc.rect(M, y, W, RH, 'F');
    }
    // Draw horizontal line for each row
    doc.line(M, y + RH, M + W, y + RH);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    st(doc, slate900);
    cells.forEach((cell, i) => {
      const isRight = i >= 2;
      const tx = isRight ? xs[i] + colW[i] - 2 : xs[i] + 2;
      doc.text(cell ?? '', tx, y + 5.5, { align: isRight ? 'right' : 'left' });
    });
    y += RH;
  });

  // Vertical lines for columns
  xs.forEach(x => doc.line(x, y - (rows.length + 1) * RH, x, y));

  return y + 6;
}

function bigTotal(doc: jsPDF, label: string, value: string, y: number, color: RGB): number {
  sf(doc, color);
  doc.rect(M, y, W, 18, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  st(doc, slate400);
  doc.text(label, M + 6, y + 7);
  doc.setFontSize(16);
  st(doc, white);
  doc.text(value, M + W - 6, y + 13, { align: 'right' });
  return y + 25;
}

function footer(doc: jsPDF) {
  const h = doc.internal.pageSize.getHeight();
  const y = h - 12;
  sd(doc, slate100);
  doc.setLineWidth(0.3);
  doc.line(M, y - 4, M + W, y - 4);
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  st(doc, slate400);
  doc.text(
    `Official Document Generated by Mtaani POS • ${new Date().toLocaleString()} • E-TIMS Certified`,
    M + W / 2, y, { align: 'center' }
  );
}

function safe(n: any): number { return Number(n) || 0; }
function ksh(n: any): string { return `Ksh ${safe(n).toLocaleString()}`; }
function safeStr(s: any, fallback = '—'): string {
  if (s === null || s === undefined) return fallback;
  return String(s) || fallback;
}

// ─── Thermal Receipt (80mm) ──────────────────────────────────────────────────
function buildReceipt(r: any, bizName = 'MTAANI POS', location = 'Nairobi, Kenya'): Blob {
  const TW = 80; // 80mm width
  const TM = 4;  // margin
  const CW = TW - TM * 2;
  
  // Dynamic height calculation
  const items = Array.isArray(r.items) ? r.items : [];
  const itemH = items.length * 8;
  const totalH = 45 + itemH + 50; // estimated
  
  const doc = new jsPDF({ unit: 'mm', format: [TW, totalH] });
  let y = 8;
  
  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  st(doc, slate900);
  doc.text(bizName.toUpperCase(), TW / 2, y, { align: 'center' });
  y += 5;
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  st(doc, slate600);
  doc.text(location, TW / 2, y, { align: 'center' });
  y += 4;
  doc.text(`Cashier: ${safeStr(r.cashierName)}`, TW / 2, y, { align: 'center' });
  y += 8;
  
  // Info
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  st(doc, slate900);
  doc.text('SALES RECEIPT', TM, y);
  y += 5;
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  st(doc, slate400);
  const ref = safeStr(r.invoiceNumber || (r.id || '').split('-')[0], 'SALE').toUpperCase();
  doc.text(`REF: ${ref}`, TM, y);
  doc.text(new Date(r.timestamp).toLocaleString('en-KE'), TW - TM, y, { align: 'right' });
  y += 5;
  
  sd(doc, slate900);
  doc.setLineWidth(0.3);
  doc.line(TM, y, TW - TM, y);
  y += 6;
  
  // Items table-like view
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  st(doc, slate900);
  doc.text('Item', TM, y);
  doc.text('Qty', TM + 35, y);
  doc.text('Price', TW - TM, y, { align: 'right' });
  y += 4;
  
  doc.setLineWidth(0.1);
  doc.line(TM, y, TW - TM, y);
  y += 5;
  
  doc.setFont('helvetica', 'normal');
  items.forEach(item => {
    const qty = safe(item.quantity);
    const price = safe(item.snapshotPrice);
    const total = qty * price;
    
    // Name (wrapped if too long)
    const name = safeStr(item.name);
    const lines = doc.splitTextToSize(name, 32);
    doc.text(lines, TM, y);
    
    doc.text(String(qty), TM + 35, y);
    doc.text(ksh(total), TW - TM, y, { align: 'right' });
    
    y += lines.length * 4 + 1;
  });
  
  y += 2;
  doc.line(TM, y, TW - TM, y);
  y += 6;
  
  // Totals
  const row = (label: string, val: string, bold = false) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(bold ? 9 : 8);
    st(doc, slate900);
    doc.text(label, TM, y);
    doc.text(val, TW - TM, y, { align: 'right' });
    y += 5;
  };
  
  row('Subtotal', ksh(r.subtotal));
  if (safe(r.discountAmount) > 0) row('Discount', `-${ksh(r.discountAmount)}`);
  row('VAT (16%)', ksh(r.tax));
  y += 2;
  row('TOTAL', ksh(r.total), true);
  
  y += 4;
  // Payment Details (Tendered & Change)
  const tethered = safe(r.amountTendered);
  if (tethered > 0) {
    row(`Paid (${r.paymentMethod || 'CASH'})`, ksh(tethered));
    const change = safe(r.changeGiven || (tethered - safe(r.total)));
    if (change > 0) {
      st(doc, green);
      row('Change', ksh(change), true);
    }
  } else if (r.paymentMethod) {
    st(doc, slate600);
    row('Paid via', r.paymentMethod);
  }

  // M-Pesa Specifics
  if (r.mpesaCode) {
    st(doc, slate600);
    row('M-Pesa Code', r.mpesaCode);
  }
  if (r.mpesaCustomer) {
    st(doc, slate600);
    row('M-Pesa Cust', r.mpesaCustomer);
  }
  
  y += 8;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  st(doc, slate400);
  doc.text('Thank you for shopping with us!', TW / 2, y, { align: 'center' });
  y += 4;
  doc.text('Keep this receipt for returns', TW / 2, y, { align: 'center' });
  
  return doc.output('blob');
}

// ─── Expense ──────────────────────────────────────────────────────────────────
function buildExpense(r: any, bizName?: string): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const ref = safeStr((r.id || '').split('-')[0], 'EXP').toUpperCase();
  let y = banner(doc, 'Expense Document', ref, new Date(r.timestamp).toLocaleString('en-KE'), bizName);
  y = hLine(doc, y);
  y = kvRow(doc, 'Category', safeStr(r.category, 'General'), y);
  y = kvRow(doc, 'Description', safeStr(r.description, 'No description provided.'), y);
  y = kvRow(doc, 'Recorded By', safeStr(r.cashierName), y);
  y = kvRow(doc, 'Status', safeStr(r.status, 'APPROVED'), y);
  y += 6;
  y = bigTotal(doc, 'AMOUNT SPENT', ksh(r.amount), y, orange);
  footer(doc);
  return doc.output('blob');
}

// ─── Purchase Order ───────────────────────────────────────────────────────────
function buildPO(r: any, supplier?: any, bizName?: string): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const ref = safeStr(r.invoiceNumber || (r.id || '').startsWith('PO-') ? r.id : (r.id || '').split('-')[0], 'LPO').toUpperCase();
  const dateStr = new Date(r.orderDate || r.timestamp || Date.now()).toLocaleDateString('en-KE', { 
    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' 
  });
  
  let y = banner(doc, 'Purchase Order', ref, dateStr, bizName);
  y = hLine(doc, y);
  
  // Supplier Info Section
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); st(doc, slate900);
  doc.text('SUPPLIER DETAILS', M, y);
  y += 6;
  y = kvRow(doc, 'Company', safeStr(supplier?.company || r.supplierName), y);
  y = kvRow(doc, 'Address', safeStr(supplier?.address), y);
  y = kvRow(doc, 'KRA PIN', safeStr(supplier?.kraPin), y);
  y = kvRow(doc, 'Contact', `${safeStr(supplier?.name)} (${safeStr(supplier?.phone)})`, y);
  y += 4;
  
  y = hLine(doc, y);
  y += 2;


  const items: any[] = Array.isArray(r.items) ? r.items : [];
  const isReceived = r.status === 'RECEIVED';
  
  const nameW = W - 10 - 24 - 30 - 30;
  const rows = items.map((item, i) => {
    const qty = isReceived ? safe(item.receivedQuantity) : safe(item.expectedQuantity);
    const cost = safe(item.unitCost);
    return [
      `${i + 1}`,
      safeStr(item.name),
      `${qty}`,
      ksh(cost),
      ksh(qty * cost),
    ];
  });

  y = table(
    doc, 
    ['#', 'Item Description', isReceived ? 'Recd' : 'Qty', 'Unit Cost', 'Subtotal'], 
    [10, nameW, 24, 30, 30], 
    rows, 
    y
  );

  y += 2;
  y = bigTotal(doc, 'GRAND TOTAL', ksh(r.totalAmount), y, slate900);
  
  // Terms & Signature
  y += 10;
  doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5); st(doc, slate900);
  doc.text('Instructions & Terms:', M, y);
  y += 6;
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); st(doc, slate600);
  doc.text('1. Please supply the above items as per the agreed unit prices and delivery schedule.', M, y);
  y += 5;
  doc.text('2. All invoices must clearly state the Purchase Order Reference number above.', M, y);
  y += 5;
  doc.text('3. This is a computer-generated document. No physical signature is required for authorization.', M, y);
  
  footer(doc);
  return doc.output('blob');
}

// ─── Supplier Remittance ──────────────────────────────────────────────────────
function buildRemittance(r: any, supplierName?: string, bizName?: string): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const ref = (r.id || '').split('-')[0].toUpperCase();
  let y = banner(doc, 'Remittance Advice', ref, new Date(r.timestamp).toLocaleString('en-KE'), bizName);
  y = hLine(doc, y);
  y = kvRow(doc, 'Supplier', safeStr(supplierName), y);
  y = kvRow(doc, 'Payment Method', safeStr(r.paymentMethod, 'CASH'), y);
  
  // Only show reference if it's NOT the auto-generated breakdown string
  const isBreakdownRef = r.reference?.toLowerCase().includes('pay inv') || r.reference?.toLowerCase().includes('less credit');
  if (r.reference && !isBreakdownRef) {
    y = kvRow(doc, 'Transaction Reference', safeStr(r.reference), y);
  }

  y = kvRow(doc, 'Recorded By', safeStr(r.preparedBy || r.cashierName), y);
  y += 6;

  const rows = [
    ...(r.invoiceDetails || []).map((i: any) => [new Date(i.date).toLocaleDateString(), 'INVOICE', String(i.ref).toUpperCase(), ksh(i.amount)]),
    ...(r.creditNoteDetails || []).map((c: any) => [new Date(c.date).toLocaleDateString(), 'CREDIT NOTE', String(c.ref).toUpperCase(), `-${ksh(c.amount)}`]),
  ];

  if (rows.length > 0) {
    y = table(doc, ['Date', 'Type', 'Reference', 'Amount'], [35, 35, 60, 52], rows, y);
    y += 2;
  }

  y = bigTotal(doc, 'TOTAL CASH REMITTED', ksh(r.amount), y, purple);

  footer(doc);
  return doc.output('blob');
}

// ─── Thermal Report (80mm) ───────────────────────────────────────────────────
function buildReport(r: any, bizName = 'MTAANI POS'): Blob {
  const TW = 80;
  const TM = 4;
  const items = [
    ['Opening Float',      ksh(r.openingFloat)],
    ['Gross Sales',        ksh(r.grossSales ?? r.totalSales)],
    ['M-Pesa Sales',       ksh(r.mpesaSales)],
    ['Cash Sales',         ksh(safe(r.grossSales ?? r.totalSales) - safe(r.mpesaSales))],
    ['Total Expenses',     `- ${ksh(r.totalExpenses)}`],
    ['Cash Bankings',      `- ${ksh(r.totalPicks)}`],
    ['VAT (16%)',          ksh(r.taxTotal)],
  ];
  
  const totalH = 40 + (items.length * 7) + 40;
  const doc = new jsPDF({ unit: 'mm', format: [TW, totalH] });
  let y = 8;

  const isDaily = r.recordType === 'DAILY_SUMMARY';
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  st(doc, slate900);
  doc.text(bizName.toUpperCase(), TW / 2, y, { align: 'center' });
  y += 5;

  doc.setFontSize(10);
  doc.text(isDaily ? 'DAILY BUSINESS AUDIT' : 'SHIFT Z-READING', TW / 2, y, { align: 'center' });
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  st(doc, slate400);
  const ref = safeStr((r.id || '').split('-')[0], 'RPT').toUpperCase();
  doc.text(`REF: ${ref}`, TM, y);
  doc.text(new Date(r.timestamp).toLocaleString('en-KE'), TW - TM, y, { align: 'right' });
  y += 6;

  sd(doc, slate900);
  doc.setLineWidth(0.3);
  doc.line(TM, y, TW - TM, y);
  y += 6;

  items.forEach(item => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    st(doc, slate600);
    doc.text(item[0], TM, y);
    st(doc, slate900);
    doc.text(item[1], TW - TM, y, { align: 'right' });
    y += 6;
  });

  y += 2;
  doc.line(TM, y, TW - TM, y);
  y += 6;

  const variance = safe(r.difference ?? r.totalVariance);
  const varOk = variance === 0;
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  st(doc, varOk ? green : red);
  doc.text(varOk ? '✓ BALANCED' : '⚠ VARIANCE', TM, y);
  doc.text(ksh(Math.abs(variance)), TW - TM, y, { align: 'right' });
  y += 6;

  if (r.cashierName) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    st(doc, slate400);
    doc.text(`Generated by: ${r.cashierName}`, TW / 2, y + 6, { align: 'center' });
  }

  return doc.output('blob');
}

// ─── Supplier Statement (A4) ──────────────────────────────────────────────────
export function buildStatementPDF(s: any, invoices: any[], payments: any[], creditNotes: any[], bizName?: string): Blob {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const dateStr = new Date().toLocaleDateString('en-KE', { day: '2-digit', month: 'short', year: 'numeric' });
  let y = banner(doc, 'Supplier Statement', (s.company || '').slice(0, 3).toUpperCase(), dateStr, bizName);
  y = hLine(doc, y);

  // Supplier Summary
  doc.setFont('helvetica', 'bold'); doc.setFontSize(10); st(doc, slate900);
  doc.text(s.company.toUpperCase(), M, y);
  y += 5;
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); st(doc, slate600);
  doc.text(`Contact: ${s.name} | Tel: ${s.phone}`, M, y);
  y += 4;
  doc.text(`Email: ${s.email || 'N/A'}`, M, y);
  y += 10;

  // Big Balance Box
  const safe = (n: any) => Number(n) || 0;
  const ksh = (n: any) => `Ksh ${safe(n).toLocaleString()}`;
  
  sf(doc, s.balance > 0 ? red : green);
  doc.rect(M, y, W, 20, 'F');
  st(doc, white);
  doc.setFontSize(9); doc.setFont('helvetica', 'bold');
  doc.text('OUTSTANDING LEDGER BALANCE', M + 6, y + 8);
  doc.setFontSize(18);
  doc.text(ksh(s.balance), M + W - 6, y + 14, { align: 'right' });
  y += 30;

  // Transaction Table
  const allTx = [
    ...(invoices || []).map(i => ({ date: i.orderDate, type: 'INVOICE', ref: i.invoiceNumber || i.id.split('-')[0], amt: i.totalAmount, bal: 'DR' })),
    ...(payments || []).map(p => ({ date: p.timestamp, type: 'PAYMENT', ref: p.reference || 'PAY', amt: p.amount, bal: 'CR' })),
    ...(creditNotes || []).map(c => ({ 
      date: c.timestamp, 
      type: 'CREDIT', 
      ref: c.reference || 'CRN', 
      amt: c.amount, 
      bal: 'CR',
      status: c.status 
    })).filter(c => c.status === 'ALLOCATED')
  ].sort((a, b) => a.date - b.date);

  let running = 0;
  const rows = allTx.map(tx => {
    if (tx.bal === 'DR') running += tx.amt;
    else running -= tx.amt;
    
    return [
      new Date(tx.date).toLocaleDateString('en-KE'),
      tx.type,
      String(tx.ref).toUpperCase(),
      tx.bal === 'DR' ? ksh(tx.amt) : '',
      tx.bal === 'CR' ? ksh(tx.amt) : '',
      ksh(running)
    ];
  });

  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); st(doc, slate900);
  doc.text('TRANSACTION HISTORY', M, y - 4);
  
  y = table(
    doc,
    ['Date', 'Type', 'Reference', 'Debit (+)', 'Credit (-)', 'Balance'],
    [25, 25, 32, 35, 35, 30],
    rows,
    y
  );

  footer(doc);
  return doc.output('blob');
}


// ─── Download trigger (works everywhere, no share sheet needed) ───────────────
function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.style.display = 'none';
  a.href = url;
  a.download = `${filename}.pdf`;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 1000);
}

// ─── Build blob by record type ────────────────────────────────────────────────
function buildPDF(record: any, supplier?: any, bizName?: string, location?: string): Blob {
  switch (record?.recordType) {
    case 'SALE':             return buildReceipt(record, bizName, location);
    case 'EXPENSE':          return buildReceipt(record, bizName, location); // fallback or buildExpense with location
    case 'PURCHASE_ORDER':   return buildPO(record, supplier, bizName);
    case 'SUPPLIER_PAYMENT': return buildRemittance(record, supplier?.company || supplier, bizName);
    case 'CLOSE_DAY_REPORT':
    case 'DAILY_SUMMARY':    return buildReport(record, bizName);
    default:                 return buildReceipt(record, bizName, location); // treat unknown as receipt
  }
}

// ─── Main export: generate + share/download ───────────────────────────────────
export async function generateAndShareDocument(
  record: any,
  filename: string,
  supplier?: any,
  forceDownload = false,
  bizName?: string,
  location?: string
): Promise<void> {
  const blob = buildPDF(record, supplier, bizName, location);
  const file = new File([blob], `${filename}.pdf`, { type: 'application/pdf' });

  // Try native share API (Android PWA, iOS Safari)
  if (
    !forceDownload &&
    typeof navigator.share === 'function' &&
    typeof navigator.canShare === 'function' &&
    navigator.canShare({ files: [file] })
  ) {
    try {
      await navigator.share({
        files: [file],
        title: `Mtaani POS — ${filename}`,
        text: `Document: ${filename}`,
      });
      return;
    } catch (err: any) {
      if (err?.name === 'AbortError') return; // user cancelled
      // Any other error → fall through to download
    }
  }

  // Fallback (desktop, unsupported browsers): trigger file download
  download(blob, filename);
}

// ─── Legacy: used by Reports tab to capture chart view ───────────────────────
export async function shareDocument(elementId: string, filename: string) {
  const { default: html2canvas } = await import('html2canvas');
  const el = document.getElementById(elementId);
  if (!el) throw new Error(`Element #${elementId} not found`);

  const canvas = await html2canvas(el, { scale: 2, backgroundColor: '#ffffff', useCORS: true });
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const pw = pdf.internal.pageSize.getWidth();
  pdf.addImage(canvas.toDataURL('image/jpeg', 0.92), 'JPEG', 0, 0, pw, (canvas.height * pw) / canvas.width, '', 'FAST');
  download(pdf.output('blob'), filename);
}

export async function generateAndDownloadStatement(s: any, invoices: any[], payments: any[], creditNotes: any[]) {
    const blob = buildStatementPDF(s, invoices, payments, creditNotes);
    download(blob, `Statement-${s.company}`);
}
